# ---------------------------------------------------------
# Makefile
# ---------------------------------------------------------
# Nidhi Parikh
# ---------------------------------------------------------
# Makefile for directory ./Figures for Paper 
# ---------------------------------------------------------

all : 

#fig1.tex : C-Vs-d-s0.dat plotFig1.gp 
#	gnuplot < plotFig1.gp 


realclean: clean

clean:
	rm -f *.pstex_t *.pstex *.tex
