pdf: thejar_biotest_10-17-16.tex
	pdflatex thejar_biotest_10-17-16.tex
dvi: thejar_biotest_10-17-16.tex
	latex thejar_biotest_10-17-16.tex
clean:
	rm -f *.log
	rm -f *.aux *.blg *.bbl *.dvi
	rm -f *.pdf
	rm -f *.tmp *.bak
	rm -f *.eps
